marsapi/mars_api/urls.py
from django.urls import path
from .views import home, get_images

app_name="mars_api"

urlpatterns = [
    path('', home, name='home'),  # Questa riga gestisce la radice del sito web
    path('<str:rover_name>/', home, name='home'),
    path('get_images/<str:rover_name>/<int:max_sol>/', get_images, name='get_images')
    
]

marsapi/marsapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mars_api.urls')),
]

marsapi/mars_api/models.py
from django.db import models

# Create your models here.

marsapi/mars_api/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from datetime import datetime
from django.core.cache import cache
from django.http import JsonResponse

import requests
import json
import random

# Create your views here.


def get_images(request, rover_name, max_sol):
    print("Sono qui")
    # Ottieni un numero casuale nell'intervallo di sol desiderato
    #rover_name = request.GET.get('rover_name')
    print(f'rover_name= {rover_name}')
    print(f'max_sol: {max_sol}')
    #max_sol = int(request.GET.get('max_sol'))  # Assicurati di convertire max_sol in un intero
    print(f'max_sol: {max_sol}')
    random_sols = [random.randint(1, max_sol) for _ in range(3)]
    
    images_list = []
    data = {}  # Inizializza il dizionario data al di fuori del ciclo
    
    for i in random_sols:
        response = requests.get(f'https://api.nasa.gov/mars-photos/api/v1/rovers/{rover_name}/photos?sol={i}&page=1&api_key={settings.NASA_API_KEY}')   
        headers = response.headers     
        #print(f'headers: {headers}')
        if response.status_code == 200:
            loaded_json = json.loads(response.text)
            #print(f"loaded_jsonaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: {loaded_json}")
            
            if 'photos' in loaded_json and len(loaded_json['photos']) > 0:
                prima_immagine = loaded_json['photos'][0]
                img_src = prima_immagine['img_src']
                earth_date = prima_immagine['earth_date']
                date_obj = datetime.strptime(earth_date, "%Y-%m-%d")
                earth_date = date_obj.strftime("%d/%m/%Y")
                sol = prima_immagine['sol']
                photo_id = loaded_json['photos'][0]['id']
                
                
                images_list.append({'img_src': img_src, 'earth_date': earth_date, 'sol': sol, 'photo_id': photo_id})
    print(f'images_list:  {images_list}')
    data = {'images_list': images_list}
    print(f'data: {data}')

    
    return JsonResponse(data, safe=False)





def home(request, rover_name='curiosity'):

    print('rover_name: {rover_name}' )
    #latest_response = requests.get(f'https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/latest_photos?api_key={settings.NASA_API_KEY}')
    background_response = requests.get(f'https://api.nasa.gov/planetary/apod?api_key={settings.NASA_API_KEY}')
    #response = requests.get(f'https://api.nasa.gov/mars-photos/api/v1/rovers/{rover_name}/photos?sol=100&page=1&api_key={settings.NASA_API_KEY}')
    response = requests.get(f'https://api.nasa.gov/mars-photos/api/v1/rovers/{rover_name}/latest_photos?api_key={settings.NASA_API_KEY}')
    #all_images_response = requests.get(f'https://api.nasa.gov/mars-photos/api/v1/rovers/{rover_name}/photos?api_key={settings.NASA_API_KEY}')
    #print(f'all_images_response.status_code: {all_images_response.status_code}')
    headers = response.headers
    #print(f'headers: {headers}')
    #print(f'latest_response: {latest_response}')
    
    loaded_background_json = json.loads(background_response.text)
    loaded_json = json.loads(response.text)
    #loaded_all_images_response = json.loads(all_images_response.text)

    #print(f'loaded_all_images_response: {loaded_all_images_response}')


    #loaded_latest_response = json.loads(latest_response.text)
    #print(f"loaded_background_json: {loaded_background_json}")
    #print(f"loaded_background_json_url: {loaded_background_json['url']}")
    #print(f"loaded_json: {loaded_json}")

    #print(f'loaded_latest_response: {loaded_latest_response}')
    background_src=loaded_background_json['url']
    rover_name = loaded_json['latest_photos'][0]['rover']['name']
    launch_date = loaded_json['latest_photos'][0]['rover']['launch_date']
    date_obj = datetime.strptime(launch_date, "%Y-%m-%d")
    launch_date = date_obj.strftime("%d/%m/%Y")
    landing_date = loaded_json['latest_photos'][0]['rover']['landing_date']
    date_obj = datetime.strptime(landing_date, "%Y-%m-%d")
    landing_date = date_obj.strftime("%d/%m/%Y")
    max_sol = loaded_json['latest_photos'][0]['rover']['max_sol']
    images_list = []
    for i in range(max_sol, max_sol - 3, -1):
        response = requests.get(f'https://api.nasa.gov/mars-photos/api/v1/rovers/{rover_name}/photos?sol={i}&page=1&api_key={settings.NASA_API_KEY}')   
        
        
        if response.status_code == 200:
            loaded_json = json.loads(response.text)
            #print(f"loaded_jsonaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: {loaded_json}")
            
            if 'photos' in loaded_json and len(loaded_json['photos']) > 0:
                prima_immagine = loaded_json['photos'][0]
                img_src = prima_immagine['img_src']
                earth_date = prima_immagine['earth_date']
                date_obj = datetime.strptime(earth_date, "%Y-%m-%d")
                earth_date = date_obj.strftime("%d/%m/%Y")
                sol = prima_immagine['sol']
                photo_id = loaded_json['photos'][0]['id']
                #print(f'photo_id: {photo_id}')
                
                
                images_list.append({'img_src': img_src, 'earth_date': earth_date, 'sol': sol, 'photo_id': photo_id})

            print(f"max_sol: {max_sol}")
  
    context = {
        'images_list': images_list,
        'background_src':background_src,
        'rover_name': rover_name,
        'launch_date': launch_date,
        'landing_date': landing_date,
        'max_sol': max_sol
        


    }

    return render(request, "mars_api/home.html", context)

marsapi/mars_api/templates/mars_api/home.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    
    <link rel="stylesheet" href="{% static '/css/style.css' %}"> 
    <style>
        body {
            background-image: url('{{ background_src }}');
            background-size: cover; /* Per adattare l'immagine allo schermo */
}
    </style>
    <title>Mars Rovers Images</title>
  </head>
  <body>
    <div class="container">
        <div id="carouselExampleFade" class="carousel slide carousel-fade mt-4" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
            <iframe src='https://mars.nasa.gov/embed/25382/' width='100%' max-height='100'  scrolling='no' frameborder='0'></iframe>
            <div class="carousel-caption d-none d-md-block">
                <h3>Select Rover</h3>
                <h3>CURIOSITY</h3>
                <a href="{% url 'mars_api:home' rover_name='curiosity' %}" class="btn text-white bg-dark bg-opacity-25">View Details</a>
            </div>
            </div>
            <div class="carousel-item">
            <iframe src='https://mars.nasa.gov/embed/21499/' width='100%' max-height='100'  scrolling='no' frameborder='0'></iframe> 
            <div class="carousel-caption d-none d-md-block">
                <h3>Select Rover</h3>
                <h3>OPPORTUNITY</h3>
                <a href="{% url 'mars_api:home' rover_name='opportunity' %}" class="btn text-white bg-dark bg-opacity-25" >View Details</a>
            </div>
            </div>
            <div class="carousel-item">
            <iframe src='https://mars.nasa.gov/embed/3507/' width='100%' max-height='100'  scrolling='no' frameborder='0'></iframe>
            <div class="carousel-caption d-none d-md-block">
                <h3>Select Rover</h3>   
                <h3>SPIRIT</h3>
                <a href="{% url 'mars_api:home' rover_name='spirit' %}" class="btn text-white bg-dark bg-opacity-25" >View Details</a>
            </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
</div>
    <div class="container" style="background-color: rgba(0, 0, 0, 0.4)">
        <div class="row">
            <div class="col-4">
                <div class="row text-center">
                    <h3 class="text-white">rover selected:</h3>
                </div>
                <div class="row text-center">
                    <h3 class="text-white">{{ rover_name }}</h3>
                </div>
                
            </div>
            <div class="col-4">
                <div class="row text-center">
                    <h3 class="text-white">launch date:</h3>
                </div>
                <div class="row text-center">
                    <h3 class="text-white">{{ launch_date }}</h3>
                </div>
                 
            </div>
            <div class="col-4">
                <div class="row text-center">
                    <h3 class="text-white">landing date:</h3>
                </div>
                <div class="row text-center">
                    <h3 class="text-white">{{ landing_date }}</h3>
                </div>
                 
            </div>
        </div>
    </div>
    
    <hr>
    
    <div class="container">
    <h3 class="text-center text-light">Mars Rovers Images</h3>
    <div class="row text-center">
        <div class="col-12 text-center">
            <button id="loadMoreButton" class="btn btn-primary" data-rover_name='{{ rover_name }}' data-max_sol="{{ max_sol }}">Carica altre immagini</button>           
            
        </div>
    </div>
    <br>

    <div class="row text-center">
        <div id="imageContainer"></div>
    </div>

    
    </div>
    
    <div class="footer mt-4">
        <div class="row">
            <div class="col-3">
            <ul>
                <li>
                <a href="https://www.linkedin.com/in/stefano-ferrari-5a79b0292/" style="text-decoration: none;">
                    <i class="bi bi-linkedin"></i> LinkedIn
                </a>

                </li>
                <li>
                
                
                <a href="https://twitter.com/rquattrogtl" style="text-decoration: none;">
                    <i class="bi bi-twitter-x"></i> twitter
                </a>

                
                </li>
                <li>
                
                
                <a href="https://github.com/r4gtl" style="text-decoration: none;">
                    <i class="bi bi-github"></i> github
                </a>
                
                </li>
            </ul>
                
                
                
            </div>
            <div class="col-3">
                
            </div>
            <div class="col-3">
                
            </div>
        </div>
    </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->

    
  </body>

  <script>
    // document.getElementById('loadMoreButton').addEventListener('click', function () {
    //var roverName = this.getAttribute('data-rover_name');
    // var maxSol = this.getAttribute('data-max_sol');

    //loadImages(roverName, maxSol);
//});
    document.addEventListener("DOMContentLoaded", function() {
    // Tutto il tuo codice JavaScript va qui
    var loadMoreButton = document.getElementById('loadMoreButton');
    var roverName = loadMoreButton.getAttribute('data-rover_name');
    var maxSol = loadMoreButton.getAttribute('data-max_sol');

    loadImages(roverName, maxSol);

    loadMoreButton.addEventListener('click', function () {
        var maxSol = 100;
        loadImages(roverName, maxSol);
    });
});


function loadImages() {
    // Recupera i dati dalla finestra di dialogo
    var roverName = $('#loadMoreButton').data('rover_name');
    var maxSol = $('#loadMoreButton').data('max_sol');
    console.log("roverName: " + roverName);
    console.log("maxSol: " + maxSol);

    // Costruisci l'URL con i parametri roverName e maxSol
    var url = '/get_images/' + roverName + '/' + maxSol + '/';

    $.get(url, function (data) {
        console.log("roverName: " + roverName);
        console.log("maxSol: " + maxSol);
        console.log("data_images: " + data.images_list);
        if (data && data.images_list && data.images_list.length > 0) {
            images = data.images_list;
            showImages(roverName);
        } else {
            console.error('Dati non validi restituiti dal server.');
        }
    });
}
function showImages(roverName) {
    var imageContainer = document.getElementById('imageContainer');
    var newImagesHTML = '<div class="row">';  // Apri una nuova riga

    for (var i = 0; i < 3; i++) {
        if (images.length > 0) {
            var image = images.pop();
            newImagesHTML += `
                <div class="col-4 text-center">
                    <div class="card card-custom mx-auto" style="max-width:60%">
                        <img src="${image.img_src}" class="card-img-top mx-auto" style="max-width: 200px; max-height: 200px;">
                        <div class="card-body text-start">
                            <p class="card-title">Sol: ${image.sol}</p>
                            <p class="card-title">Earth Date: ${image.earth_date}</p>
                            <p class="card-title">Rover ${roverName}</p>
                            <p class="card-title">Photo #${image.photo_id}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="${image.img_src}" class="btn btn-primary text-center" target="_blank">View Image</a>
                        </div>
                    </div>
                </div>
            `;
        }
    }

    newImagesHTML += '</div>';  // Chiudi la riga

    // Sostituisci il contenuto di imageContainer con il nuovo HTML
    imageContainer.innerHTML = newImagesHTML;
}


function showImages_old() {
    var imageContainer = document.getElementById('imageContainer');
    for (var i = 0; i < 3; i++) {
        if (images.length > 0) {
            var image = images.pop();
            var cardDiv = document.createElement('div');
            cardDiv.className = 'col-4 text-center';
            cardDiv.innerHTML = `
                <div class="col-4 text-center">
                    <div class="card card-custom mx-auto" style="max-width:60%">
                        <img src="${ image.img_src }" class="card-img-top mx-auto" style="max-width: 200px; max-height: 200px;">
                        <div class="card-body text-start">
                            <h5 class="card-title">Sol: ${ image.sol }</h5>
                            <h5 class="card-title">Earth Date: {{ image.earth_date }}</h5>
                            <p class="card-title">Photo #${ image.photo_id }</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="${ image.img_src }$" class="btn btn-primary text-center" target="_blank">View Image</a>
                        </div>
                    </div>
                </div>
                
            `;
            imageContainer.appendChild(cardDiv);
        }
    }
}


</script>


</html>